#src/Producer_api/app/schemas/protobuf/number_id_v1.py
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08v1.proto\x12\x0ciotcrypto.v1\"K\n\tMessageV1\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06iot_id\x18\x02 \x01(\t\x12\x11\n\tcrypto_id\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vnumber_id_v1', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEV1._serialized_start=26
  _MESSAGEV1._serialized_end=101
# @@protoc_insertion_point(module_scope)
