#src/Producer_api/app/schemas/protobuf/string_id_v1.py
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08v2.proto\x12\x0ciotcrypto.v2\"\xb5\x01\n\tMessageV2\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06iot_id\x18\x02 \x01(\t\x12\x11\n\tcrypto_id\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x37\n\x08metadata\x18\x05 \x03(\x0b\x32%.iotcrypto.v2.MessageV2.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'string_id_v1', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEV2_METADATAENTRY._options = None
  _MESSAGEV2_METADATAENTRY._serialized_options = b'8\001'
  _MESSAGEV2._serialized_start=27
  _MESSAGEV2._serialized_end=208
  _MESSAGEV2_METADATAENTRY._serialized_start=161
  _MESSAGEV2_METADATAENTRY._serialized_end=208
# @@protoc_insertion_point(module_scope)
